# Generated by Django 5.2.13 on 2026-04-28 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dentista',
                'verbose_name_plural': 'Dentistas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cita', models.CharField(editable=False, help_text='Formato CIT-YYYYMMDD-NNN', max_length=20, unique=True)),
                ('nombre_paciente', models.CharField(max_length=80)),
                ('dni_paciente', models.CharField(max_length=8)),
                ('telefono', models.CharField(max_length=9)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], max_length=5)),
                ('motivo', models.CharField(choices=[('Limpieza', 'Limpieza'), ('Extraccion', 'Extraccion'), ('Endodoncia', 'Endodoncia'), ('Ortodoncia', 'Ortodoncia'), ('Revision general', 'Revision general')], max_length=20)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Cancelada', 'Cancelada')], default='Activa', max_length=10)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='citas.dentista')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
