# Generated by Django 5.2.14 on 2026-05-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'Activa')), fields=('fecha', 'hora', 'dentista'), name='unique_turno_activo_por_dentista'),
        ),
    ]
